import Head from 'next/head'
import Image from 'next/image'
// import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>Text Styles</h2>
          <h5>Font: Work Sans</h5>
          <h1>H1 - NFT Marketplace</h1>
          <h2>H2 - NFT Marketplace</h2>
          <h3>H3 - NFT Marketplace</h3>
          <h4>H4 - NFT Marketplace</h4>
          <h5>H5 - NFT Marketplace</h5>
          <h6>H6 - NFT Marketplace</h6>
          <p>Base - NFT Marketplace</p>
          <p className="caption">Caption - NFT Marketplace</p>
          <br />
          <br />
          <br />
          <h5>Font: Space Mono</h5>
          <h1 className="ffs">NFT Marketplace</h1>
          <h2 className="ffs">NFT Marketplace</h2>
          <h3 className="ffs">NFT Marketplace</h3>
          <h4 className="ffs">NFT Marketplace</h4>
          <h5 className="ffs">NFT Marketplace</h5>
          <h6 className="ffs">NFT Marketplace</h6>
          <p className="ffs">NFT Marketplace</p>
          <p className="ffs caption">NFT Marketplace</p>
          <br />
          <br />
          <br />
          <br />
          <br />
          <h2>Color Palette</h2>
          <h4>Background & Text</h4>
          <div className="group">
            <div className="bg-1"></div>
            <div className="bg-2"></div>
            <div className="bg-3"></div>
            <div className="bg-4"></div>
          </div>
          <h4>Call to action</h4>
          <div className="group">
            <div className="bg-action"></div>
          </div>
          <h4>Gradient</h4>
          <div className="group">
            <div className="gradient-1"></div>
            <div className="gradient-2"></div>
          </div>
          <br />
          <br />
          <br />
          <br />
          <br />
          <h2>Buttons</h2>
          <h4>Primary</h4>
          <div className="group">
            <button className="btn-primary">
              <img src='https://svgshare.com/i/qNj.svg' title='' />
              <p>Button</p>
            </button>
            <button className="btn-alt">
              <img src='https://svgshare.com/i/qNj.svg' title='' />
              <p>Button</p>
            </button>
            <p>TODO : transform img to font and change color for alt btn</p>

          </div>
          <h4>Secondary</h4>
          <div className="group">
            <button className="btn-secondary">
              <img src='https://svgshare.com/i/qNj.svg' title='' />
              <p>Button</p>
            </button>
            <button className="btn-secondary btn-alt">
              <img src='https://svgshare.com/i/qNj.svg' title='' />
              <p>Button</p>
            </button>
            <p>TODO : transform img to font and change color for alt btn</p>
          </div>
          <h4>Tertiary</h4>
          <div className="group">
            <button className="btn-tertiary">
              <img src='https://svgshare.com/i/qNj.svg' title='' />
              <p>Button</p>
            </button>
            <button className="btn-tertiary btn-alt">
              <img src='https://svgshare.com/i/qNj.svg' title='' />
              <p>Button</p>
            </button>
            <p>TODO : transform img to font and change color for alt btn</p>
          </div>

          <h4>Icons</h4>
          <p>TODO : transform img to font</p>
          <br />
          <br />
          <br />
          <br />
          <h2>Avatars</h2>
          <img className="avatar" src="https://via.placeholder.com/728x400 " />
        </div>

        <div>
          <Image
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
      </main>
    </>
  )
}
